### PR TITLE
Enabled adb over ethernet

### PR DESCRIPTION
**Pull request by Kishore409**
Enabling adb over ethernet for SKL devices

Bug Id: https://01.org/jira/browse/AIA-67
Test: adb devices and adb shell works from the host

Signed-off-by: Abhilash K V <abhilash.k.v@intel.com>
Signed-off-by: Kishore Kadiyala <kishore.kadiyala@intel.com>

### CODE REVIEW

**Comment by Kishore409** [comment]
@kalyankondapally

**Comment by Kishore409** [comment]
@shobhitka @shobhitka , plz review and merge if no comments

**Comment by tpalli** [comment]
I've been using adb over ethernet for some months now, it works already?

**Comment by shobhitka** [comment]
Made necessary changes to indicate this is not specific to SKL but for all builds and merged. Security aspect will need further changes as incremental patches or revert.

**Comment by shobhitka** [comment]
Reverted this patch as this is not correct patch as we need to stop and start adb with this as well. Also if we do this, adb over USB will be not work.

**Comment by shobhitka** [comment]
Verified that both usb and ethernet can work together on Joule. adb start is happening in the init.rc flow after setting property

**Pull request merged**
