### PR TITLE
Add relative_sleep_states option to cmdline

### PR DESCRIPTION
**Pull request by abhilashkesavan**
Some atom platforms do not support ACPI S1/S3 and so freeze (S2I) is the
only available system sleep state.  However, android uses the "mem" sleep
state label and this prevents the system from suspending altogether.
Use the relative_sleep_states commandline parameter to map "freeze" state
to "mem".

Jira: None
Test: 1) Boot the platform to android home screen
      2) Press the power button/wait for display timeout after disabling
      "Stay awake" in "Developer options"
      3) From the serial logs verify that the system has triggered S2I

Signed-off-by: Abhilash Kesavan <abhilash.kesavan@intel.com>

### CODE REVIEW

**Comment by abhilashkesavan** [comment]
Please pick this or https://github.com/android-ia/device-androidia-kernel/pull/11. Either one of them will work.

**Comment by kalyankondapally** [comment]
lets go with kernel changes  android-ia/device-androidia-kernel#11.

**Comment by abhilashkesavan** [comment]
OK, thanks Kalyan. Do upstream backports need Test and JIRA fields ? I have forgotten to add them in android-ia/device-androidia-kernel#11.

**Comment by kalyankondapally** [comment]
Kernel patch merged

**Pull request closed without merging**
