### PR TITLE
change the mount point for config partition

### PR DESCRIPTION
**Pull request by eht25g**
we can't mount the config partition to /config
because it's used for usb configfs mount point since Android N.
Otherwise it will cause the unmount_and_fsck failed
and wasted 5 seconds during shutdown.

So, change the mount point from /config to /oem_config

JIRA: None
Test: use command 'mount' to check the mount points
      we should see the mmcblkp11 mounted on /oem_config

Signed-off-by: Ting Li <ting.li@intel.com>

### CODE REVIEW

**Comment by eht25g** [comment]
@kalyankondapally Hi, Kalyan, could you please review this patch?

**Comment by eht25g** [comment]
Change the USB configfs mount point to /config is not done by us but Google, so we have to make changes to fit it.

**Comment by kalyankondapally** [comment]
does this need any changes in liveinstaller ?

**Comment by shobhitka** [comment]
Guess no change in liveinstaller. But IIRC the fstab was coming from existing projects and it was expected at /config. Are we sure that once we make oem_config as the vendor config mount point Google's code uses oem_config to look for it.  Have we tested with a valid vendor configuration ? 

I don't remember now but not sure if updating AndroidBoard.mk is enough to create the mount point in ramdisk.img as well. We might have  to create that as well if not already created.

**Comment by kalyankondapally** [comment]
No other changes are needed, fstab was something we populated and got adaptation as use cases got adapted. @sgnanase @Kishore409 Can you validate the change.

**Comment by shobhitka** [comment]
I created the initial fstab and that was based on existing projects to mount vendor config at /config IIRC. Anyways validate and if it is all well we can merge.

**Comment by sgnanase** [comment]
Merged...

**Pull request closed without merging**
