### PR TITLE
Update mixins for enabling MTP & PTP over type-C

### PR DESCRIPTION
**Pull request by a-k-v**
JIRA: https://01.org/jira/browse/AIA-265
Tests: Mixin update is successful;MTP file transfer works.

Signed-off-by: Abhilash K V <abhilash.k.v@intel.com>

### CODE REVIEW

**Comment by kalyankondapally** [comment]
@Kishore409 ping for validation.

**Comment by Kishore409** [comment]
@a-k-v We tried the patch
MTP :
•	Detected
•	the copy progress bar does not close/end. (End of file issue)
        The copied files are confirmed only we remove the type-c and connect back
         (seems to be sync issue)
PTP :
•	When switched to PTP from the drop menu in the notification bar , the device is not detected by the host device
MTP to PTP:
PTP doesn't work
PTP to MTP:
Firstly PTP doesn't work and when switched to MTP , PTP folders are shown

Ideally Standalone MTP, PTP , switching should work.

**Comment by a-k-v** [comment]
@Kishore409 , Yes, the kernel WA ( https://github.com/android-ia/device-androidia-kernel/pull/12) fixes the MTP rx issue. Please review and help merge.

**Comment by kalyankondapally** [comment]
@Kishore409 ping

**Comment by Kishore409** [comment]
@a-k-v Merged , Thanks

**Pull request merged**
