### PR TITLE
Fix: Enable serial on Joule

### PR DESCRIPTION
**Pull request by harishkrupo**
Can be used as a fallback when adb doesn't work.

JIRA: AIA-220
Test: Console shows up on serial.

Signed-off-by: Harish Krupo <harish.krupo.kps@intel.com>

### CODE REVIEW

**Comment by harishkrupo** [comment]
@kalyankondapally Could you please check this now?

**Comment by Kishore409** [comment]
@shobhitka plz review and merge if no comments

**Comment by shobhitka** [comment]
You should squash the two commits and send pull request again. And why this is enabled only in user builds and not in eng builds ?

**Comment by harishkrupo** [comment]
It is not equal to.

**Comment by harishkrupo** [comment]
@shobhitka Changes done.
Also this patch is required https://github.com/android-ia/device-androidia/pull/42

**Comment by shobhitka** [comment]
Merged

**Pull request merged**
