### PR TITLE
Summary : [Android-IA] Increase system partition size.

### PR DESCRIPTION
**Pull request by sgnanase**
Fix  : Increase system partition size to 3GB.

Jira :None

Test : Able to flash system partition, build boots to home screen.

Signed-off-by: sgnanase <sundar.gnanasekaran@intel.com>

### CODE REVIEW

**Comment by shobhitka** [comment]
Looks okay, but please rebase and push again.

**Comment by kalyankondapally** [comment]
No need to rebase, merged the patch but forgot to close pull request.

**Comment by kalyankondapally** [comment]
Sorry no, need to fix this myself

**Comment by kalyankondapally** [comment]
Now merged.

**Pull request closed without merging**
