### PR TITLE
Fix: Kernel modules copy in vendor.img

### PR DESCRIPTION
**Pull request by harishkrupo**
This dependency ensures the kernel modules are built
and copied to the vendor directory before the vendor.img
is built.

Jira: AIA-123
Test: The vendor.img file contains all the kernel modules.

Signed-off-by: Harish Krupo <harish.krupo.kps@intel.com>

### CODE REVIEW

**Comment by kalyankondapally** [comment]
@Kishore409 @harishkrupo Still couple of issue:
1) Live works fine now with grub, however when trying to install u see a complaint /lib/modules path not found.
2)If you delete out/target/product/androidia_64/vendor and do incremental build (also removing vendor.img) modules are not copied to vendor/lib/modules folder again.

**Comment by harishkrupo** [comment]
Issue 1 is fixed: PR: https://github.com/android-ia/bootable-live-installer/pull/11

**Comment by kalyankondapally** [comment]
Now we are back to normal where nothing works again @harishkrupo Can u test with grub builds.

**Comment by kalyankondapally** [comment]
merged

**Pull request closed without merging**
