### PR TITLE
FSTAB and GPT changes for KF Integration

### PR DESCRIPTION
**Pull request by shobhitka**
Everything was mostly already pulled in. Main issues - 
1. mixin.spec is reffering the android-ia rather than EFI so fstab needed to be updated for that
2. Same issue was there for watchdog paramete which is updated in efi/BoardConfig.mk but not in android-ia/BoardConfig.mk

### CODE REVIEW

**Comment by kalyankondapally** [comment]
@shobhitka  We cannot do the fstab change untill we can get Grub to work with the same. For now there is some manual work involved, we need to update the mixins groups here, run ./device/intel/mixins/mixin-update script, this will generate changes to device/intel/android_ia/android_ia-64 folder. You would need to commit those changes and upload them to device/android_ia. Eventually, we would like to automate this via CI bot and one needs to just upload changes to mixins

**Comment by shobhitka** [comment]
@kalyankondapally fstab is not being used by Grub solution yet, so it does not matter even if we update right now. Eventually they will use same and this is the first step towards that. Updating initrd to use the same is not far away anyway.

Secondly on mixins side, do you mean that we should make changes directly in android_ia-64 folder and commit rather putting in mixin right now. I think instead of making things deviate from what they would be in future is probably not right. Since running mixin-update is setting up everything nicely, why not just maually run mixin-update till CI gets it automated.

Thirdly if we go with mixin-update as above, then b56746b this does not work for android-ia in mixin.spec. So we need it in there as well. Right now it adds only if mixin.spec chooses efi.

**Comment by kalyankondapally** [comment]
fstab does impact with Grub shobhit, Did you locally try this ? 

Reg Mixin:
Yes we need to make changes to mixin and androidia_64.

**Comment by shobhitka** [comment]
Oops, updated my comment while you were commenting. I think it should not make an impact, but I will try today and confirm. At worst I expect mount to fail thats all if you do not have the gpt burnt already on the device. If you have, then ofcourse it will break things.

**Comment by kalyankondapally** [comment]
Merged

**Pull request closed without merging**
