### PR TITLE
Update fstab and gpt.ini to support both KF and Grub based boot

### PR DESCRIPTION
**Pull request by shobhitka**
This allows common gpt.ini and fstab to be used in both ways of booting

### CODE REVIEW

**Comment by kalyankondapally** [comment]
@shobhitka Live works but when I tried installation it got broke :(  When I reboot after installing it fails to find the OS, infact I dont even go to the grub menu at all

**Comment by shobhitka** [comment]
@kalyankondapally, can you give me the logs of installation, or can you install on another pen drive and analyze with the partitions that are being created there and are they as per the gpt.ini file ?

**Comment by kalyankondapally** [comment]
@shobhitka Can you rebase the patches ? Seems like most of them are already merged.

@tpalli @txu4 @cmsanta Anyone want to test this ?

**Comment by shobhitka** [comment]
@kalyankondapally okay I will work on rebasing this and pushing again. And I found the issue which you might have faced. Guess I forgot to commit the gpt.ini for this pull request. Have fixed that and will send a new pull request.

@tpalli , @txu4 , @cmsanta , please wait for new pull request before testing.

**Comment by shobhitka** [comment]
This pull request needs additional updates and rebase on latest code. Closing the same. Another will be sent.

**Pull request closed without merging**
